/**
 * P1: Tag CRUD 完备测试
 * Tags CRUD requires admin role.
 */
import { createHash, randomBytes } from 'crypto'
import { describe, it, expect, beforeAll, afterAll } from 'vitest'
import { buildApp } from '../src/app.js'
import { prisma, makeGroup, makeTag, makeEntity, attachTag } from './helpers.js'

let app: ReturnType<typeof buildApp>
let adminToken: string

function sha256(raw: string) { return createHash('sha256').update(raw).digest('hex') }
function newRawToken() { return 'ct_' + randomBytes(16).toString('hex') }

beforeAll(async () => {
  app = buildApp({ silent: true })
  const raw = newRawToken()
  await prisma.apiToken.create({ data: { name: 'crud-admin', tokenHash: sha256(raw), role: 'admin', scopes: [] } })
  adminToken = raw
})
afterAll(async () => {
  await prisma.apiToken.deleteMany()
})

function bearer(token: string): HeadersInit { return { Authorization: `Bearer ${token}` } }

async function post(path: string, body: unknown) {
  const res = await app.request(path, { method: 'POST', headers: { 'Content-Type': 'application/json', ...bearer(adminToken) }, body: JSON.stringify(body) })
  return { status: res.status, body: await res.json() as Record<string, unknown> }
}
async function patch(path: string, body: unknown) {
  const res = await app.request(path, { method: 'PATCH', headers: { 'Content-Type': 'application/json', ...bearer(adminToken) }, body: JSON.stringify(body) })
  return { status: res.status, body: await res.json() as Record<string, unknown> }
}
async function del(path: string) {
  const res = await app.request(path, { method: 'DELETE', headers: bearer(adminToken) })
  return { status: res.status, body: await res.json() as Record<string, unknown> }
}
async function get(path: string) {
  const res = await app.request(path, { headers: bearer(adminToken) })
  return { status: res.status, body: await res.json() as Record<string, unknown> }
}

describe('POST /tags (admin)', () => {
  it('creates a tag', async () => {
    const g = await makeGroup()
    const r = await post('/tags', { groupId: g.id, name: 'Spicy', slug: 'spicy' })
    expect(r.status).toBe(200)
    expect((r.body as { code: number }).code).toBe(0)
  })

  it('rejects duplicate slug in same group', async () => {
    const g = await makeGroup()
    await makeTag({ groupId: g.id, slug: 'spicy' })
    const r = await post('/tags', { groupId: g.id, name: 'Spicy2', slug: 'spicy' })
    expect(r.status).toBe(409)
  })

  it('rejects duplicate name in same group', async () => {
    const g = await makeGroup()
    await makeTag({ groupId: g.id, name: 'Spicy' })
    const r = await post('/tags', { groupId: g.id, name: 'Spicy', slug: 'spicy2' })
    expect(r.status).toBe(409)
  })

  it('allows same slug in different groups', async () => {
    const g1 = await makeGroup()
    const g2 = await makeGroup()
    await makeTag({ groupId: g1.id, slug: 'spicy' })
    const r = await post('/tags', { groupId: g2.id, name: 'Spicy', slug: 'spicy' })
    expect(r.status).toBe(200)
  })

  it('rejects non-existent group', async () => {
    const r = await post('/tags', { groupId: 'nonexistent', name: 'X', slug: 'x' })
    expect(r.status).toBe(404)
  })

  it('auto-generates slug when not provided', async () => {
    const g = await makeGroup()
    const r = await post('/tags', { groupId: g.id, name: 'AutoGenerated' })
    expect(r.status).toBe(200)
    const data = (r.body as { data: { slug: string } }).data
    expect(data.slug.length).toBeGreaterThan(0)
  })
})

describe('PATCH /tags/:id (admin)', () => {
  it('renames a tag', async () => {
    const g = await makeGroup()
    const t = await makeTag({ groupId: g.id, slug: 'old', name: 'Old' })
    const r = await patch(`/tags/${t.id}`, { name: 'New', slug: 'new' })
    expect(r.status).toBe(200)
  })

  it('rejects rename to duplicate name', async () => {
    const g = await makeGroup()
    const t1 = await makeTag({ groupId: g.id, slug: 'a', name: 'A' })
    const t2 = await makeTag({ groupId: g.id, slug: 'b', name: 'B' })
    const r = await patch(`/tags/${t1.id}`, { name: 'B' })
    expect(r.status).toBe(409)
  })

  it('returns 404 for non-existent tag', async () => {
    const r = await patch('/tags/nonexistent', { name: 'X' })
    expect(r.status).toBe(404)
  })

  it('returns 400 when nothing to update', async () => {
    const g = await makeGroup()
    const t = await makeTag({ groupId: g.id })
    const r = await patch(`/tags/${t.id}`, {})
    expect(r.status).toBe(400)
  })
})

describe('DELETE /tags/:id (admin)', () => {
  it('soft-deletes a tag', async () => {
    const g = await makeGroup()
    const t = await makeTag({ groupId: g.id })
    const r = await del(`/tags/${t.id}`)
    expect(r.status).toBe(200)
    // Not accessible
    const g2 = await get(`/tags/${t.id}`)
    expect(g2.status).toBe(404)
  })

  it('soft-deleted tag does not block recreation', async () => {
    const g = await makeGroup()
    const t = await makeTag({ groupId: g.id, slug: 'reusable' })
    await del(`/tags/${t.id}`)
    const r = await post('/tags', { groupId: g.id, name: 'Reused', slug: 'reusable' })
    expect(r.status).toBe(200)
  })

  it('cascades on hard delete', async () => {
    const g = await makeGroup()
    const t = await makeTag({ groupId: g.id })
    const e = await makeEntity('dish', 'dish-del-test')
    await attachTag({ tagId: t.id, entityType: 'dish', entityId: e.entityId })
    const r = await del(`/tags/${t.id}?permanent=true&force=true`)
    expect(r.status).toBe(200)
    // EntityTag should cascade-delete with hard delete
    const count = await prisma.entityTag.count({ where: { tagId: t.id } })
    expect(count).toBeLessThanOrEqual(1)
  })
})

describe('POST /tags/:id/restore (admin)', () => {
  it('restores a soft-deleted tag', async () => {
    const g = await makeGroup()
    const t = await makeTag({ groupId: g.id, slug: 'restorable', name: 'Restorable' })
    await del(`/tags/${t.id}`)
    const r = await post(`/tags/${t.id}/restore`, {})
    expect(r.status).toBe(200)
    const g2 = await get(`/tags/${t.id}`)
    expect(g2.status).toBe(200)
  })

  it('returns 404 for non-existent tag', async () => {
    const r = await post('/tags/nonexistent/restore', {})
    expect(r.status).toBe(404)
  })
})

describe('GET /tags (list)', () => {
  it('returns paginated tags', async () => {
    const g = await makeGroup()
    await Promise.all([makeTag({ groupId: g.id, slug: 'a', name: 'A' }), makeTag({ groupId: g.id, slug: 'b', name: 'B' })])
    const r = await get(`/tags?groupId=${g.id}`)
    expect(r.status).toBe(200)
    const data = (r.body as { data: { items: unknown[]; total: number } }).data
    expect(data.total).toBe(2)
  })

  it('filters by parentId', async () => {
    const g = await makeGroup()
    const parent = await makeTag({ groupId: g.id, slug: 'parent', name: 'Parent' })
    await post('/tags', { groupId: g.id, name: 'Child', slug: 'child', parentId: parent.id })
    const r = await get(`/tags?groupId=${g.id}&parentId=${parent.id}`)
    const data = (r.body as { data: { total: number } }).data
    expect(data.total).toBe(1)
  })

  it('filters by q', async () => {
    const g = await makeGroup()
    await Promise.all([makeTag({ groupId: g.id, slug: 'spicy', name: 'Spicy' }), makeTag({ groupId: g.id, slug: 'mild', name: 'Mild' })])
    const r = await get(`/tags?groupId=${g.id}&q=Spicy`)
    const data = (r.body as { data: { total: number } }).data
    expect(data.total).toBe(1)
  })
})

describe('GET /tags/:id/ancestors', () => {
  it('returns ancestor chain', async () => {
    const g = await makeGroup()
    const root = await makeTag({ groupId: g.id, slug: 'root', name: 'Root' })
    const childRes = await post('/tags', { groupId: g.id, name: 'Child', slug: 'child', parentId: root.id })
    const tId = ((childRes.body as { data: { id: string } }).data).id
    const r = await get(`/tags/${tId}/ancestors`)
    expect(r.status).toBe(200)
    const data = (r.body as { data: { id: string }[] }).data
    expect(data.length).toBe(1)
    expect(data[0].id).toBe(root.id)
  })
})
