/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/entities/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 审核队列 */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    pageSize?: number;
                    /** @description 状态过滤（pending/active/rejected） */
                    status?: string;
                    entityType?: string;
                    reviewerId?: string;
                    /** @description ISO 日期，reviewedAt >= */
                    from?: string;
                    /** @description ISO 日期，reviewedAt <= */
                    to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            data: {
                                items: {
                                    tagId: string;
                                    entityType: string;
                                    entityId: string;
                                    source: string;
                                    confidence: number | null;
                                    status: string;
                                    taggedAt: string;
                                    reviewedAt: string | unknown;
                                    reviewNote: string | null;
                                    reviewerName: string | null;
                                    tag: {
                                        id: string;
                                        slug: string;
                                        name: string;
                                        group: {
                                            id: string;
                                            slug: string;
                                            name: string;
                                        };
                                    };
                                }[];
                                total: number;
                                page: number;
                                pageSize: number;
                            };
                        };
                    };
                };
                /** @description 参数错误 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities/{entityType}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出实体（支持标签过滤） */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    pageSize?: number;
                    /** @description 标签 ID 过滤（可多个） */
                    tagId?: string;
                    /** @description 按标签名称模糊过滤 */
                    q?: string;
                    /** @description 按 entityId 模糊搜索 */
                    search?: string;
                    withTags?: "true" | "false";
                };
                header?: never;
                path: {
                    entityType: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            data: {
                                items: {
                                    entityType: string;
                                    entityId: string;
                                    registeredAt?: string;
                                    tags?: {
                                        id: string;
                                        slug: string;
                                        name: string;
                                        groupId: string;
                                        group: {
                                            id: string;
                                            slug: string;
                                            name: string;
                                        };
                                        source: string;
                                        confidence: number | null;
                                        status: string;
                                        taggedAt: string;
                                    }[];
                                }[];
                                total: number;
                                page: number;
                                pageSize: number;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities/{entityType}/{entityId}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取实体标签列表 */
        get: {
            parameters: {
                query?: {
                    status?: "active" | "pending" | "rejected" | "all";
                };
                header?: never;
                path: {
                    entityType: string;
                    entityId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            data: {
                                id: string;
                                slug: string;
                                name: string;
                                groupId: string;
                                group: {
                                    id: string;
                                    slug: string;
                                    name: string;
                                };
                                source: string;
                                confidence: number | null;
                                status: string;
                                taggedAt: string;
                            }[];
                        };
                    };
                };
                /** @description 实体未注册 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                        };
                    };
                };
            };
        };
        /** 全量替换实体标签 */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    entityType: string;
                    entityId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        tagIds: string[];
                        /**
                         * @default manual
                         * @enum {string}
                         */
                        source?: "manual" | "ai" | "system" | "import";
                        confidence?: number | null;
                        /** @enum {string} */
                        status?: "active" | "pending" | "rejected";
                    };
                };
            };
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                        };
                    };
                };
                /** @description 参数错误 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                        };
                    };
                };
                /** @description 标签不合法 */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                        };
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities/{entityType}/{entityId}/tags/{tagId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 增量打标（单个） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    entityType: string;
                    entityId: string;
                    tagId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        tagId: string;
                        /**
                         * @default manual
                         * @enum {string}
                         */
                        source?: "manual" | "ai" | "system" | "import";
                        confidence?: number | null;
                        note?: string;
                    };
                };
            };
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                        };
                    };
                };
                /** @description 参数错误 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                        };
                    };
                };
                /** @description 标签不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                        };
                    };
                };
                /** @description 已打标 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                        };
                    };
                };
                /** @description 不允许多选 */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                        };
                    };
                };
            };
        };
        /** 摘标 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    entityType: string;
                    entityId: string;
                    tagId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                        };
                    };
                };
                /** @description 关联不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** 审核标签状态 */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    entityType: string;
                    entityId: string;
                    tagId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "active" | "pending" | "rejected";
                        note?: string | null;
                    };
                };
            };
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                        };
                    };
                };
                /** @description 参数错误 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                        };
                    };
                };
                /** @description 关联不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/entities/{entityType}/{entityId}/tags/{tagId}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取审核历史时间线 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    entityType: string;
                    entityId: string;
                    tagId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            data: {
                                id: string;
                                fromStatus: string;
                                toStatus: string;
                                note: string | null;
                                reviewedAt: string;
                                reviewer: {
                                    id: string;
                                    name: string;
                                    role: string;
                                } | null;
                            }[];
                        };
                    };
                };
                /** @description 关联不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities/{entityType}/{entityId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询实体是否已注册 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 实体类型，如 dish / dining */
                    entityType: string;
                    /** @description 实体唯一标识符 */
                    entityId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            data: {
                                entityType: string;
                                entityId: string;
                                registeredAt?: string;
                                tags?: {
                                    id: string;
                                    slug: string;
                                    name: string;
                                    groupId: string;
                                    group: {
                                        id: string;
                                        slug: string;
                                        name: string;
                                    };
                                    source: string;
                                    confidence: number | null;
                                    status: string;
                                    taggedAt: string;
                                }[];
                            };
                        };
                    };
                };
                /** @description 未注册 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        /** 注册实体 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 实体类型，如 dish / dining */
                    entityType: string;
                    /** @description 实体唯一标识符 */
                    entityId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 注册成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                        };
                    };
                };
            };
        };
        /** 注销实体（级联删除所有标签关联） */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 实体类型，如 dish / dining */
                    entityType: string;
                    /** @description 实体唯一标识符 */
                    entityId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                        };
                    };
                };
                /** @description 未注册 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tag-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出分组 */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    pageSize?: number;
                    /** @description 按实体类型过滤 */
                    scope?: string;
                    withPreviewTags?: "true" | "false";
                    previewSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            data: {
                                items: {
                                    id: string;
                                    slug: string;
                                    name: string;
                                    description: string | null;
                                    entityScopes: string[];
                                    allowMultiple: boolean;
                                    sortOrder: number;
                                    createdAt: string;
                                    updatedAt: string;
                                    deletedAt?: string | unknown;
                                    entityRules?: {
                                        groupId: string;
                                        entityType: string;
                                        allowMultiple: boolean;
                                    }[];
                                    _count?: {
                                        tags: number;
                                    };
                                }[];
                                total: number;
                                page: number;
                                pageSize: number;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        /** 创建分组 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        slug: string;
                        name: string;
                        description?: string;
                        /** @default [] */
                        entityScopes?: string[];
                        /** @default false */
                        allowMultiple?: boolean;
                        /** @default 0 */
                        sortOrder?: number;
                    };
                };
            };
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            data: {
                                id: string;
                                slug: string;
                                name: string;
                                description: string | null;
                                entityScopes: string[];
                                allowMultiple: boolean;
                                sortOrder: number;
                                createdAt: string;
                                updatedAt: string;
                                deletedAt?: string | unknown;
                                entityRules?: {
                                    groupId: string;
                                    entityType: string;
                                    allowMultiple: boolean;
                                }[];
                                _count?: {
                                    tags: number;
                                };
                            };
                        };
                    };
                };
                /** @description 参数错误 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                        };
                    };
                };
                /** @description 冲突 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tag-groups/{groupId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取分组详情 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 标签分组 ID */
                    groupId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            data: {
                                id: string;
                                slug: string;
                                name: string;
                                description: string | null;
                                entityScopes: string[];
                                allowMultiple: boolean;
                                sortOrder: number;
                                createdAt: string;
                                updatedAt: string;
                                deletedAt?: string | unknown;
                                entityRules?: {
                                    groupId: string;
                                    entityType: string;
                                    allowMultiple: boolean;
                                }[];
                                _count?: {
                                    tags: number;
                                };
                            };
                        };
                    };
                };
                /** @description 不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** 删除分组（软删除） */
        delete: {
            parameters: {
                query?: {
                    force?: "1" | "true";
                };
                header?: never;
                path: {
                    /** @description 标签分组 ID */
                    groupId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                        };
                    };
                };
                /** @description 不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                        };
                    };
                };
                /** @description 有关联数据 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** 更新分组 */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 标签分组 ID */
                    groupId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        slug?: string;
                        name?: string;
                        description?: string;
                        entityScopes?: string[];
                        allowMultiple?: boolean;
                        sortOrder?: number;
                    };
                };
            };
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            data: {
                                id: string;
                                slug: string;
                                name: string;
                                description: string | null;
                                entityScopes: string[];
                                allowMultiple: boolean;
                                sortOrder: number;
                                createdAt: string;
                                updatedAt: string;
                                deletedAt?: string | unknown;
                                entityRules?: {
                                    groupId: string;
                                    entityType: string;
                                    allowMultiple: boolean;
                                }[];
                                _count?: {
                                    tags: number;
                                };
                            };
                        };
                    };
                };
                /** @description 不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                        };
                    };
                };
                /** @description 冲突 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/tag-groups/{groupId}/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取分组完整标签树 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 标签分组 ID */
                    groupId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            data: unknown[];
                        };
                    };
                };
                /** @description 不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tag-groups/{groupId}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取分组内标签（分页） */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    pageSize?: number;
                };
                header?: never;
                path: {
                    /** @description 标签分组 ID */
                    groupId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            data: {
                                items: {
                                    id: string;
                                    groupId: string;
                                    slug: string;
                                    name: string;
                                    description: string | null;
                                    parentId: string | null;
                                    path: string;
                                    depth: number;
                                    sortOrder: number;
                                    createdAt: string;
                                    updatedAt: string;
                                    deletedAt?: string | unknown;
                                    group?: {
                                        id: string;
                                        slug: string;
                                        name: string;
                                    };
                                    _count?: {
                                        entityTags: number;
                                    };
                                }[];
                                total: number;
                                page: number;
                                pageSize: number;
                            };
                        };
                    };
                };
                /** @description 不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tag-groups/{groupId}/entity-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 设置实体类型规则 */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 标签分组 ID */
                    groupId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        rules: {
                            entityType: string;
                            allowMultiple: boolean;
                        }[];
                    };
                };
            };
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            data: {
                                groupId: string;
                                entityType: string;
                                allowMultiple: boolean;
                            }[];
                        };
                    };
                };
                /** @description 不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                        };
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 按 name/slug/alias 解析标签 */
        get: {
            parameters: {
                query: {
                    /** @description 查询词（name、slug 或 alias） */
                    q: string;
                    /** @description 限定分组范围 */
                    groupId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            data: {
                                tag: {
                                    id: string;
                                    groupId: string;
                                    slug: string;
                                    name: string;
                                    description: string | null;
                                    parentId: string | null;
                                    path: string;
                                    depth: number;
                                    sortOrder: number;
                                    createdAt: string;
                                    updatedAt: string;
                                    deletedAt?: string | unknown;
                                    group?: {
                                        id: string;
                                        slug: string;
                                        name: string;
                                    };
                                    _count?: {
                                        entityTags: number;
                                    };
                                };
                                /** @enum {string} */
                                matchedBy: "name" | "slug" | "alias";
                            };
                        };
                    };
                };
                /** @description 参数错误 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                        };
                    };
                };
                /** @description 未找到 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出标签（支持按分组、名称过滤、分页） */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    pageSize?: number;
                    groupId?: string;
                    /** @description 'null' 表示只返回根节点 */
                    parentId?: string;
                    /** @description 按名称模糊搜索 */
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            data: {
                                items: {
                                    id: string;
                                    groupId: string;
                                    slug: string;
                                    name: string;
                                    description: string | null;
                                    parentId: string | null;
                                    path: string;
                                    depth: number;
                                    sortOrder: number;
                                    createdAt: string;
                                    updatedAt: string;
                                    deletedAt?: string | unknown;
                                    group?: {
                                        id: string;
                                        slug: string;
                                        name: string;
                                    };
                                    _count?: {
                                        entityTags: number;
                                    };
                                }[];
                                total: number;
                                page: number;
                                pageSize: number;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        /** 创建标签 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        groupId: string;
                        name: string;
                        slug?: string;
                        description?: string;
                        parentId?: string;
                        /** @default 0 */
                        sortOrder?: number;
                    };
                };
            };
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            data: {
                                id: string;
                                groupId: string;
                                slug: string;
                                name: string;
                                description: string | null;
                                parentId: string | null;
                                path: string;
                                depth: number;
                                sortOrder: number;
                                createdAt: string;
                                updatedAt: string;
                                deletedAt?: string | unknown;
                                group?: {
                                    id: string;
                                    slug: string;
                                    name: string;
                                };
                                _count?: {
                                    entityTags: number;
                                };
                            };
                        };
                    };
                };
                /** @description 参数错误 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                        };
                    };
                };
                /** @description 分组不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                        };
                    };
                };
                /** @description 冲突 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags/{tagId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取单个标签详情 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 标签 ID */
                    tagId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            data: {
                                id: string;
                                groupId: string;
                                slug: string;
                                name: string;
                                description: string | null;
                                parentId: string | null;
                                path: string;
                                depth: number;
                                sortOrder: number;
                                createdAt: string;
                                updatedAt: string;
                                deletedAt?: string | unknown;
                                group?: {
                                    id: string;
                                    slug: string;
                                    name: string;
                                };
                                _count?: {
                                    entityTags: number;
                                };
                            };
                        };
                    };
                };
                /** @description 不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** 删除标签（软删除） */
        delete: {
            parameters: {
                query?: {
                    force?: "1" | "true";
                };
                header?: never;
                path: {
                    /** @description 标签 ID */
                    tagId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                        };
                    };
                };
                /** @description 不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                        };
                    };
                };
                /** @description 有关联数据 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** 更新标签 */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 标签 ID */
                    tagId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name?: string;
                        slug?: string;
                        description?: string;
                        parentId?: string | null;
                        sortOrder?: number;
                    };
                };
            };
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            data: {
                                id: string;
                                groupId: string;
                                slug: string;
                                name: string;
                                description: string | null;
                                parentId: string | null;
                                path: string;
                                depth: number;
                                sortOrder: number;
                                createdAt: string;
                                updatedAt: string;
                                deletedAt?: string | unknown;
                                group?: {
                                    id: string;
                                    slug: string;
                                    name: string;
                                };
                                _count?: {
                                    entityTags: number;
                                };
                            };
                        };
                    };
                };
                /** @description 参数错误 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                        };
                    };
                };
                /** @description 不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                        };
                    };
                };
                /** @description 冲突 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/tags/{tagId}/descendants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取所有子孙标签 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 标签 ID */
                    tagId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            data: {
                                items: {
                                    id: string;
                                    groupId: string;
                                    slug: string;
                                    name: string;
                                    description: string | null;
                                    parentId: string | null;
                                    path: string;
                                    depth: number;
                                    sortOrder: number;
                                    createdAt: string;
                                    updatedAt: string;
                                    deletedAt?: string | unknown;
                                    group?: {
                                        id: string;
                                        slug: string;
                                        name: string;
                                    };
                                    _count?: {
                                        entityTags: number;
                                    };
                                }[];
                                total: number;
                            };
                        };
                    };
                };
                /** @description 不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags/{tagId}/ancestors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取祖先链（从根到父，不含自身） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 标签 ID */
                    tagId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            data: {
                                id: string;
                                slug: string;
                                name: string;
                                depth: number;
                            }[];
                        };
                    };
                };
                /** @description 不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags/{targetId}/merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 合并标签（同分组）
         * @description 将多个源标签合并到目标标签，迁移 EntityTag 和 Alias，软删除源标签。源标签不能有子节点。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    targetId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description 要合并进 target 的源标签 ID 列表 */
                        sourceIds: string[];
                    };
                };
            };
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            data: {
                                entityTagsMoved: number;
                                aliasesMoved: number;
                            };
                        };
                    };
                };
                /** @description 参数错误 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                        };
                    };
                };
                /** @description 标签不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                        };
                    };
                };
                /** @description 冲突（如源标签有子节点） */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags/{tagId}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 迁移标签到另一分组（含子孙） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tagId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description 目标分组 ID */
                        targetGroupId: string;
                        /** @description 目标分组内的父节点 ID，null 表示成为根节点 */
                        newParentId?: string | null;
                    };
                };
            };
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            data: {
                                tag: {
                                    id: string;
                                    groupId: string;
                                    slug: string;
                                    name: string;
                                    description: string | null;
                                    parentId: string | null;
                                    path: string;
                                    depth: number;
                                    sortOrder: number;
                                    createdAt: string;
                                    updatedAt: string;
                                    deletedAt?: string | unknown;
                                    group?: {
                                        id: string;
                                        slug: string;
                                        name: string;
                                    };
                                    _count?: {
                                        entityTags: number;
                                    };
                                };
                                tagsMoved: number;
                            };
                        };
                    };
                };
                /** @description 参数错误 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                        };
                    };
                };
                /** @description 不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                        };
                    };
                };
                /** @description 冲突 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags/{tagId}/aliases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出标签别名 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 标签 ID */
                    tagId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            data: {
                                id: string;
                                tagId: string;
                                alias: string;
                                source: string;
                                createdAt: string;
                            }[];
                        };
                    };
                };
                /** @description 标签不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        /** 添加别名 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 标签 ID */
                    tagId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        alias: string;
                        /**
                         * @default manual
                         * @enum {string}
                         */
                        source?: "manual" | "ai" | "import";
                    };
                };
            };
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            data: {
                                id: string;
                                tagId: string;
                                alias: string;
                                source: string;
                                createdAt: string;
                            };
                        };
                    };
                };
                /** @description 标签不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                        };
                    };
                };
                /** @description 别名冲突 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags/{tagId}/aliases/{aliasId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 删除别名 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tagId: string;
                    /** @description 别名 ID */
                    aliasId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                        };
                    };
                };
                /** @description 不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出所有 Token */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            data: {
                                id: string;
                                name: string;
                                role: string;
                                scopes: string[];
                                createdAt: string;
                                lastUsedAt: string | unknown;
                                revokedAt: string | unknown;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        /** 创建 Token（一次性返回明文） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                        /**
                         * @default reader
                         * @enum {string}
                         */
                        role?: "admin" | "writer" | "reviewer" | "reader";
                        /** @default [] */
                        scopes?: string[];
                    };
                };
            };
            responses: {
                /** @description 成功，token 字段仅此一次可见 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            data: {
                                id: string;
                                name: string;
                                role: string;
                                scopes: string[];
                                createdAt: string;
                                lastUsedAt: string | unknown;
                                revokedAt: string | unknown;
                                /** @description 一次性明文 token，创建后不可再查 */
                                token: string;
                            };
                        };
                    };
                };
                /** @description 参数错误 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tokens/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 撤销 Token */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                        };
                    };
                };
                /** @description 不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 多维检索（布尔表达式 + 分页 + facet）
         * @description 基于 BoolExpr DSL 检索实体：支持 and/or/not 嵌套、按 tag/slug/alias/descendantOf 匹配、按 source/confidence/status 过滤。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description 实体类型，必填 */
                        entityType: string;
                        filter?: components["schemas"]["BoolExpr"];
                        /**
                         * @description 页码
                         * @default 1
                         */
                        page?: number;
                        /**
                         * @description 每页条数
                         * @default 20
                         */
                        pageSize?: number;
                        /**
                         * @description 排序字段
                         * @default registeredAt:desc
                         * @enum {string}
                         */
                        sort?: "registeredAt:desc" | "registeredAt:asc" | "taggedAt:desc" | "taggedAt:asc";
                        /**
                         * @description 附加返回字段
                         * @default []
                         */
                        include?: "tags"[];
                        /**
                         * @description 需要聚合的 facet 维度
                         * @default []
                         */
                        facets?: "groupId"[];
                    };
                };
            };
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            data: {
                                items: {
                                    entityType: string;
                                    entityId: string;
                                    registeredAt: string;
                                    tags?: {
                                        id: string;
                                        slug: string;
                                        name: string;
                                        groupId: string;
                                        group: {
                                            id: string;
                                            slug: string;
                                            name: string;
                                        };
                                        source: string;
                                        confidence: number | null;
                                        status: string;
                                        taggedAt: string;
                                    }[];
                                }[];
                                total: number;
                                page: number;
                                pageSize: number;
                                facets?: {
                                    [key: string]: {
                                        [key: string]: {
                                            tagId: string;
                                            tagSlug: string;
                                            tagName: string;
                                            groupId: string;
                                            count: number;
                                        }[];
                                    };
                                };
                            };
                        };
                    };
                };
                /** @description 参数错误 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description 标签布尔表达式（缺省=全集） */
        BoolExpr: {
            tag: string;
        } | {
            tagSlug: string;
            groupSlug?: string;
        } | {
            tagAlias: string;
            groupSlug?: string;
        } | {
            descendantOf: string;
        } | {
            source: ("manual" | "ai" | "system" | "import")[];
        } | {
            confidence: {
                gte?: number;
                lte?: number;
            };
        } | {
            status: ("active" | "pending" | "rejected")[];
        } | {
            and: components["schemas"]["BoolExpr"][];
        } | {
            or: components["schemas"]["BoolExpr"][];
        } | {
            not: components["schemas"]["BoolExpr"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
